name: Launch Jupyter Notebook
on:
  push:
    branches:
      - main
jobs:
   launch-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch Jupyter Notebook
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jupyter
          jupyter-notebook --no-browser --ip=0.0.0.0 --port=8888 stable_diffusion (1).ipynb
