name: Launch Jupyter Notebook
on:
  push:
    branches:
      - main
jobs:
   launch-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch Jupyter Notebook
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jupyter
          jupyter-notebook --no-browser --ip=0.0.0.0 --port=8888 stable_diffusion (1).ipynb
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the step that prints the file contents here
      - name: Print file contents
        run: cat /path/to/file.txt

      - name: Install dependencies
        run: |
          npm install
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
